student_sheet_url = "https://docs.google.com/spreadsheets/d/1jTpwqncjDpA8FxOFj4ZiFzi_XY7lxjwO7SUCAzRfGtA"
drive_folder_id = "1fn45BNyBQ1JQoHW1gXcXVKYO_BHq7Di3"

[gcp_service_account]
type = "service_account"
project_id = "edulx-455410"
private_key_id = "432de66b458d0562aa3636fc1fec34f6572d85e2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDiYenEyiTn4kl0
75ooPhVoIqZJu4MdUmKLQwVy6c7WNAvc+alYMlkeRXA6N6O/Teya2+PmcBUx8tA/
8f/A5JhEZOdShhxmYajWRM2MUOT6DU8hCut0kFSF7hGqA2eN0/9mV+s4VoKeasZ9
gRyXf+9PO5vRi9lfZ2YtoeCUO4hvKRAfPgb8WxyMrOkgABwIjP9h81K+7mgthigX
R9aksITR9yoYKO4Q6elWl2D1NAgWFRXxLrutoa4ko/Uov7Rm7hz0vv5Saop95qv/
McLId8aPBWRcK1/xAQBEBpiq/W4S4uYz8wLQpnEapt8P+m0S0SkL4OzPEszB0WEh
05YIy2LXAgMBAAECggEAHbmi6xFqlygXYnYI/+URr9gc4uxEOG1rkxhRzCz3Lm6B
wETn/4oHjvn/KnsefS12NpSjmsvM0f+Cvg1rT6C0fbE3eUEy1B6uqgk5aYXrCwpZ
rDUK2wYN6H1sxFjTbW67cmzI7got9y8osQIVsa7oIAyWVoV5HWsuTNTx8C+A/Vdf
rOHkgzyaBr/4cU1obxxFFV2faiBCesUc0XRQ4w4OemmRSHvFWgPoRfrJolZd0w+5
fDsPat2BbEXirykbvw5qqw18G+t+jcv6CeYyvYiCUsnZZrRTfXEsehEPeoHNZhR3
flXNwir9lJ7/3AEF2wYrqQ3AENVXzFVbwyeuLvKHgQKBgQD89YJM3tyRyo+FyAmq
ASkxIMiAP+/oe+9Jf4qM+ACjLBtyxk5bUNgQK78NCRFOW7G1GakN8TBkdnIAVm6m
KrSRyzyIpfPj73QGpDGWcBgvk2a4f2vSyuJq+qF0a6qTvjfM4GYnlAfMcHid3K0r
LDLLbZqRiKomAAEkBDvFDephnwKBgQDlGp0kqY8fzNgoC7Xl4Dgg3lHy3tXS5pgm
qudXvBvOCg0wFE0w7A+PGIIHDqT7SsN4mk1nbnkDlB2tv/Uu/nDxxbUEqkEHYXiu
ENHJEiX//3ZTeLNZNsx/iHT2NXLTbrZvolOd1fGNHXh0R4E+Neioh4tXRXRfoH/0
CWuCkBQjyQKBgQCDz9K0B7Vb6vdauOAATFaQmQqhea+jr2EDJYim6Fw8qrEq35bZ
Eolj88e8HSt9b15shhCHiVS0JNxGvMMvpzUse4Dxm7g43//PriOAxqxzrhVqsksX
Lk1JfYxARBJApnAhPBU/Lm3Z5AmWCPXbd06InnZau6Id5waxI9uZVST69QKBgH+e
FY7IjJswJfAYpdhIz7svXAKnsf/qxzIy3O74L5zT6IixplXsCLay9issMyZvfPb/
LMLCvNILfYS9erwUq6FhefYBSHvuBaUgZVtVqqkxCh5xC6ZUahFYV56WI0I3V5RT
nbQ76nOqyOAsvIeEy/akmi+g1rQ12VB8ttBhpXZRAoGBAKd+KskbKddjedT4N75t
6/N/d6KVJ3MndQDXqHUyHUQERl5sUMbkJggCenjvhIgt7yExYphF7KTm+683T9kW
eQB3QwJZmtqxN8bCP3jb6k1XRexxm3ViyL47ohfXmRWN8fydhIiKQLAhdmBDn9fi
5c5fnTa/HFCtK60sPKO4/Min
-----END PRIVATE KEY-----"""
client_email = "edulx-955@edulx-455410.iam.gserviceaccount.com"
client_id = "118133361697007555307"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/edulx-955%40edulx-455410.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
